drivers: soc: qcom: minidump_log: Fix type specifier missing
../drivers/soc/qcom/minidump_log.c:111:8: error: type specifier missing, defaults to 'int' [-Werror,-Wimplicit-int]
static md_align_offset;
~~~~~~ ^

Signed-off-by: LowTension <zonarmr@gmail.com>